[package]
name = "rust1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.27"
rand = "0.8.4"
flate2 = "1.0"
reqwest = "0.11.6"
tokio = { version = "1", features = ["full"] }

